### ISSUE TITLE
Broken Url

### ISSUE THREAD

**Issue by tyler489** [ldtteam/MinecoloniesWiki#555] opened 2021-01-28 04:48 UTC
## Description
https://ldtteam.github.io/MinecoloniesWiki/source/systems/research
Has several broken Hyperlinks that refer to Gates

specifically gate research 1 and 2

**Comment by ravenbuilder934** [comment] 2021-01-28 04:49
Duplicate of #493

**Closed by ravenbuilder934** 2021-01-28 04:49 UTC
Labels: Bug
