### ISSUE TITLE
World Generation Colonies

### ISSUE THREAD

**Issue by Skeletonlp** [ldtteam/MinecoloniesWiki#1018] opened 2024-01-05 22:34 UTC
this Statement seems to be incorret ,because of changes in how world generation works in minecraft.can now be found as a datapack:

As you explore the world, you’ll notice that there are some colonies abandoned by the former residents. Moving into one of these abandoned colonies is a way to quickstart your own colony!

(Note: This feature is only available in 1.18+. Vanilla villages will still spawn as normal. If you wish to turn off this feature, you can do so in the [configuration options](https://wiki.minecolonies.ldtteam.com/source/misc/configfile) for your world.)

**Comment by Thodor12** [comment] 2024-01-05 22:35
Duplicate of #1017

**Closed by Thodor12** 2024-01-05 22:35 UTC
Labels: Inaccurate Info
